# Generated by Django 3.2.8 on 2021-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_dwollacustomer_dwollafundingsource_dwollatransfersource_plaidtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwollacustomer',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
